export const GATEWAY_PACKAGE_ROOT_FILES = [
  "package.json",
  "JWW_GATEWAY_MANIFEST.json",
  "README.md",
  "README.ja.md",
  "JWW_GATEWAY_HANDOFF.md",
  "jww-gateway-convert.cmd",
  "jww-gateway-coverage.cmd",
  "jww-gateway-coverage-summary.cmd",
  "jww-gateway-core-open-summary.cmd",
  "jww-gateway-diagnose.cmd",
  "jww-gateway-diff.cmd",
  "jww-gateway-env-scan.cmd",
  "jww-gateway-jwf-compare.cmd",
  "jww-gateway-jwf-parse.cmd",
  "jww-gateway-jwf-value-scan.cmd",
  "jww-gateway-layer-defaults-audit.cmd",
  "jww-gateway-layer-defaults-summary.cmd",
  "jww-gateway-sample-plan.cmd",
  "jww-gateway-special-color-audit.cmd",
  "jww-gateway-special-color-summary.cmd",
  "jww-gateway-status.cmd",
  "jww-gateway-validate.cmd",
  "jww-gateway-verify-all.cmd",
  "jww-gateway-verify-diff.cmd",
  "jww-gateway-verify-handoff.cmd",
  "jww-gateway-open-items.cmd",
  "jww-gateway-report-index.cmd",
  "jww-gateway-verify-report.cmd",
  "reports/.gitkeep",
  "reports/README.md",
];

export const GATEWAY_PACKAGE_TOOL_FILES = [
  "jww-gateway.mjs",
  "jww-coverage.mjs",
  "jww-coverage-summary.mjs",
  "jww-diagnostics.mjs",
  "jww-diagnostics-diff.mjs",
  "jww-schema-validate.mjs",
  "jww-env-scan.mjs",
  "jwf-parse.mjs",
  "jww-jwf-compare.mjs",
  "jww-jwf-value-scan.mjs",
  "jww-layer-defaults-audit.mjs",
  "jww-layer-defaults-summary.mjs",
  "jww-special-color-audit.mjs",
  "jww-special-color-summary.mjs",
  "jww-value-scan-summary.mjs",
  "jww-core-open-summary.mjs",
  "jww-sample-plan.mjs",
  "jww-gateway-open-items.mjs",
  "jww-gateway-report-index.mjs",
  "jww-manifest-validate.mjs",
  "jww-gateway-status.mjs",
  "jww-gateway-verify-report.mjs",
  "jww-gateway-verify-report-diff.mjs",
  "jww-gateway-smoke.mjs",
];

export const GATEWAY_PACKAGE_DOC_FILES = [
  "jww-gateway-json.schema.json",
  "jww-gateway-manifest.schema.json",
  "jww-gateway-sample-sets.schema.json",
  "JWW_GATEWAY_SPEC.md",
  "JWW_JWF_ENV_AUDIT.md",
  "JWW_GATEWAY_RELEASE_CHECKLIST.md",
  "JWW_GATEWAY_RELEASE_NOTES.md",
  "JWW_GATEWAY_REPORTS.md",
  "JWW_GATEWAY_HANDOFF.md",
  "JWW_GATEWAY_WINDOWS_COMMANDS.md",
  "JWW_GATEWAY_SAMPLE_SETS.example.json",
];

export const GATEWAY_PACKAGE_SRC_FILES = [
  "parser.js",
  "parser.test.js",
  "decoder.js",
  "decoder.test.js",
  "environment.js",
  "environment.test.js",
  "jwf.js",
  "jwf.test.js",
  "jwfValueScan.js",
  "jwfValueScan.test.js",
  "valueScanSummary.js",
  "valueScanSummary.test.js",
  "coreOpenSummary.js",
  "coreOpenSummary.test.js",
  "layerDefaultsSummary.js",
  "layerDefaultsSummary.test.js",
  "gatewayManifest.js",
  "gatewayManifest.test.js",
  "gatewayPackageFiles.js",
  "shared.js",
  "schemaValidator.test.js",
  "testHarness.js",
  "arcDiagnostics.js",
  "BinaryReader.js",
];

export function packageRequiredFiles() {
  return [
    ...GATEWAY_PACKAGE_ROOT_FILES,
    ...GATEWAY_PACKAGE_TOOL_FILES.map((file) => `tools/${file}`),
    ...GATEWAY_PACKAGE_DOC_FILES.map((file) => `docs/${file}`),
    ...GATEWAY_PACKAGE_SRC_FILES.map((file) => `src/jww/${file}`),
  ];
}
